naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Z0-9]*'

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]

complexity:
  LongParameterList:
    functionThreshold: 8
